namespace ACBindingsTest.Internal;

// AMMO_TYPE
public enum AMMO_TYPE : uint
{
    AMMO_NONE = 0x0,
    AMMO_ARROW = 0x1,
    AMMO_BOLT = 0x2,
    AMMO_ATLATL = 0x4,
    AMMO_ARROW_CRYSTAL = 0x8,
    AMMO_BOLT_CRYSTAL = 0x10,
    AMMO_ATLATL_CRYSTAL = 0x20,
    AMMO_ARROW_CHORIZITE = 0x40,
    AMMO_BOLT_CHORIZITE = 0x80,
    AMMO_ATLATL_CHORIZITE = 0x100,
    FORCE_AMMO_TYPE_32_BIT = 0x7FFFFFFF
}

