namespace ACBindingsTest.Internal;

// ATTRIBUTE_CACHE_MASK
public enum ATTRIBUTE_CACHE_MASK : uint
{
    UNDEF_MASK = 0x0,
    STRENGTH_MASK = 0x1,
    ENDURANCE_MASK = 0x2,
    QUICKNESS_MASK = 0x4,
    COORDINATION_MASK = 0x8,
    FOCUS_MASK = 0x10,
    SELF_MASK = 0x20,
    HEALTH_MASK = 0x40,
    STAMINA_MASK = 0x80,
    MANA_MASK = 0x100,
    FORCE_ATTRIBUTE_CACHE_MASK_32_BIT = 0x7FFFFFFF
}

