namespace ACBindingsTest.Internal;

// CG_VERIFICATION_RESPONSE
public enum CG_VERIFICATION_RESPONSE : uint
{
    UNDEF_CG_VERIFICATION_RESPONSE = 0x0,
    CG_VERIFICATION_RESPONSE_OK = 0x1,
    CG_VERIFICATION_RESPONSE_PENDING = 0x2,
    CG_VERIFICATION_RESPONSE_NAME_IN_USE = 0x3,
    CG_VERIFICATION_RESPONSE_NAME_BANNED = 0x4,
    CG_VERIFICATION_RESPONSE_CORRUPT = 0x5,
    CG_VERIFICATION_RESPONSE_DATABASE_DOWN = 0x6,
    CG_VERIFICATION_RESPONSE_ADMIN_PRIVILEGE_DENIED = 0x7,
    NUM_CG_VERIFICATION_RESPONSES = 0x8,
    FORCE_CG_VERIFICATION_RESPONSE_32_BIT = 0x7FFFFFFF
}

