namespace ACBindingsTest.Internal;

// charError
public enum charError : uint
{
    CHAR_ERROR_UNDEF = 0x0,
    CHAR_ERROR_LOGON = 0x1,
    CHAR_ERROR_LOGGED_ON = 0x2,
    CHAR_ERROR_ACCOUNT_LOGON = 0x3,
    CHAR_ERROR_SERVER_CRASH = 0x4,
    CHAR_ERROR_LOGOFF = 0x5,
    CHAR_ERROR_DELETE = 0x6,
    CHAR_ERROR_NO_PREMADE = 0x7,
    CHAR_ERROR_ACCOUNT_IN_USE = 0x8,
    CHAR_ERROR_ACCOUNT_INVALID = 0x9,
    CHAR_ERROR_ACCOUNT_DOESNT_EXIST = 0xA,
    CHAR_ERROR_ENTER_GAME_GENERIC = 0xB,
    CHAR_ERROR_ENTER_GAME_STRESS_ACCOUNT = 0xC,
    CHAR_ERROR_ENTER_GAME_CHARACTER_IN_WORLD = 0xD,
    CHAR_ERROR_ENTER_GAME_PLAYER_ACCOUNT_MISSING = 0xE,
    CHAR_ERROR_ENTER_GAME_CHARACTER_NOT_OWNED = 0xF,
    CHAR_ERROR_ENTER_GAME_CHARACTER_IN_WORLD_SERVER = 0x10,
    CHAR_ERROR_ENTER_GAME_OLD_CHARACTER = 0x11,
    CHAR_ERROR_ENTER_GAME_CORRUPT_CHARACTER = 0x12,
    CHAR_ERROR_ENTER_GAME_START_SERVER_DOWN = 0x13,
    CHAR_ERROR_ENTER_GAME_COULDNT_PLACE_CHARACTER = 0x14,
    CHAR_ERROR_LOGON_SERVER_FULL = 0x15,
    CHAR_ERROR_CHARACTER_IS_BOOTED = 0x16,
    CHAR_ERROR_ENTER_GAME_CHARACTER_LOCKED = 0x17,
    CHAR_ERROR_SUBSCRIPTION_EXPIRED = 0x18,
    CHAR_ERROR_NUM_ERRORS = 0x19,
    FORCE_charError_32_BIT = 0x7FFFFFFF
}

