namespace ACBindingsTest.Internal;

// IMPORT_OBJECT_NAME_TYPE
public enum IMPORT_OBJECT_NAME_TYPE : byte
{
    IMPORT_OBJECT_ORDINAL = 0x0,
    IMPORT_OBJECT_NAME = 0x1,
    IMPORT_OBJECT_NAME_NO_PREFIX = 0x2,
    IMPORT_OBJECT_NAME_UNDECORATE = 0x3
}

