namespace ACBindingsTest.Internal;

// PlayerOption
public enum PlayerOption : uint
{
    AutoRepeatAttack_PlayerOption = 0x0,
    IgnoreAllegianceRequests_PlayerOption = 0x1,
    IgnoreFellowshipRequests_PlayerOption = 0x2,
    IgnoreTradeRequests_PlayerOption = 0x3,
    DisableMostWeatherEffects_PlayerOption = 0x4,
    PersistentAtDay_PlayerOption = 0x5,
    AllowGive_PlayerOption = 0x6,
    ViewCombatTarget_PlayerOption = 0x7,
    ShowTooltips_PlayerOption = 0x8,
    UseDeception_PlayerOption = 0x9,
    ToggleRun_PlayerOption = 0xA,
    StayInChatMode_PlayerOption = 0xB,
    AdvancedCombatUI_PlayerOption = 0xC,
    AutoTarget_PlayerOption = 0xD,
    VividTargetingIndicator_PlayerOption = 0xE,
    FellowshipShareXP_PlayerOption = 0xF,
    AcceptLootPermits_PlayerOption = 0x10,
    FellowshipShareLoot_PlayerOption = 0x11,
    FellowshipAutoAcceptRequests_PlayerOption = 0x12,
    SideBySideVitals_PlayerOption = 0x13,
    CoordinatesOnRadar_PlayerOption = 0x14,
    SpellDuration_PlayerOption = 0x15,
    DisableHouseRestrictionEffects_PlayerOption = 0x16,
    DragItemOnPlayerOpensSecureTrade_PlayerOption = 0x17,
    DisplayAllegianceLogonNotifications_PlayerOption = 0x18,
    UseChargeAttack_PlayerOption = 0x19,
    UseCraftSuccessDialog_PlayerOption = 0x1A,
    HearAllegianceChat_PlayerOption = 0x1B,
    DisplayDateOfBirth_PlayerOption = 0x1C,
    DisplayAge_PlayerOption = 0x1D,
    DisplayChessRank_PlayerOption = 0x1E,
    DisplayFishingSkill_PlayerOption = 0x1F,
    DisplayNumberDeaths_PlayerOption = 0x20,
    DisplayTimeStamps_PlayerOption = 0x21,
    SalvageMultiple_PlayerOption = 0x22,
    HearGeneralChat_PlayerOption = 0x23,
    HearTradeChat_PlayerOption = 0x24,
    HearLFGChat_PlayerOption = 0x25,
    HearRoleplayChat_PlayerOption = 0x26,
    AppearOffline_PlayerOption = 0x27,
    DisplayNumberCharacterTitles_PlayerOption = 0x28,
    MainPackPreferred_PlayerOption = 0x29,
    LeadMissileTargets_PlayerOption = 0x2A,
    UseFastMissiles_PlayerOption = 0x2B,
    FilterLanguage_PlayerOption = 0x2C,
    ConfirmVolatileRareUse_PlayerOption = 0x2D,
    HearSocietyChat_PlayerOption = 0x2E,
    ShowHelm_PlayerOption = 0x2F,
    DisableDistanceFog_PlayerOption = 0x30,
    UseMouseTurning_PlayerOption = 0x31,
    ShowCloak_PlayerOption = 0x32,
    LockUI_PlayerOption = 0x33,
    TotalNumberOfPlayerOptions_PlayerOption = 0x34,
    Invalid_PlayerOption = 0xFFFFFFFF
}

