namespace ACBindingsTest.Internal;

// RMFieldType
public enum RMFieldType : byte
{
    RMFIELD_LAYER_DIFFUSE = 0x0,
    RMFIELD_LAYER_SPECULAR = 0x1,
    RMFIELD_LAYER_SPECULARPOWER = 0x2,
    RMFIELD_LAYER_DYE = 0x3,
    RMFIELD_LAYER_CULLMODE = 0x4,
    RMFIELD_LAYER_DEPTHTEST = 0x5,
    RMFIELD_LAYER_DEPTHWRITE = 0x6,
    RMFIELD_LAYER_ALPHATEST = 0x7,
    RMFIELD_LAYER_ALPHATESTREF = 0x8,
    RMFIELD_LAYER_STAGE_TEXTURE = 0x9,
    RMFIELD_LAYER_STAGE_ADDRESSMODEU = 0xA,
    RMFIELD_LAYER_STAGE_ADDRESSMODEV = 0xB,
    RMFIELD_LAYER_MOD_ORIGIN_XTRANSLATE = 0xC,
    RMFIELD_LAYER_MOD_ORIGIN_YTRANSLATE = 0xD,
    RMFIELD_LAYER_MOD_ORIGIN_ZTRANSLATE = 0xE,
    RMFIELD_LAYER_MOD_ORIGIN_XSCALE = 0xF,
    RMFIELD_LAYER_MOD_ORIGIN_YSCALE = 0x10,
    RMFIELD_LAYER_MOD_ORIGIN_ZSCALE = 0x11,
    RMFIELD_LAYER_MOD_ORIGIN_ORIGINPHASE = 0x12,
    RMFIELD_LAYER_MOD_ORIGIN_NORMALPHASE = 0x13,
    RMFIELD_LAYER_MOD_NORMAL_XTRANSLATE = 0x14,
    RMFIELD_LAYER_MOD_NORMAL_YTRANSLATE = 0x15,
    RMFIELD_LAYER_MOD_NORMAL_ZTRANSLATE = 0x16,
    RMFIELD_LAYER_MOD_NORMAL_XSCALE = 0x17,
    RMFIELD_LAYER_MOD_NORMAL_YSCALE = 0x18,
    RMFIELD_LAYER_MOD_NORMAL_ZSCALE = 0x19,
    RMFIELD_LAYER_MOD_NORMAL_ORIGINPHASE = 0x1A,
    RMFIELD_LAYER_MOD_NORMAL_NORMALPHASE = 0x1B,
    RMFIELD_LAYER_MOD_DIFFUSE_R = 0x1C,
    RMFIELD_LAYER_MOD_DIFFUSE_G = 0x1D,
    RMFIELD_LAYER_MOD_DIFFUSE_B = 0x1E,
    RMFIELD_LAYER_MOD_DIFFUSE_A = 0x1F,
    RMFIELD_LAYER_MOD_UVTRANSLATE_UTRANSLATE = 0x20,
    RMFIELD_LAYER_MOD_UVTRANSLATE_VTRANSLATE = 0x21,
    RMFIELD_LAYER_MOD_UVROTATE_ROTATE = 0x22,
    RMFIELD_LAYER_MOD_UVSCALE_USCALE = 0x23,
    RMFIELD_LAYER_MOD_UVSCALE_VSCALE = 0x24
}

