namespace ACBindingsTest.Internal;

// SKILL_CATEGORY
public enum SKILL_CATEGORY : uint
{
    UNDEF_SKILL_CATEGORY = 0x0,
    WEAPON_SKILL_CATEGORY = 0x1,
    NONWEAPON_SKILL_CATEGORY = 0x2,
    MAGIC_SKILL_CATEGORY = 0x3,
    NUM_SKILL_CATEGORIES = 0x4,
    FORCE_SKILL_CATEGORY_32_BIT = 0x7FFFFFFF
}

