namespace ACBindingsTest.Internal;

// TextureOp
public enum TextureOp : uint
{
    TEXOP_DISABLE = 0x1,
    TEXOP_SELECTARG1 = 0x2,
    TEXOP_SELECTARG2 = 0x3,
    TEXOP_MODULATE = 0x4,
    TEXOP_MODULATE2X = 0x5,
    TEXOP_MODULATE4X = 0x6,
    TEXOP_ADD = 0x7,
    TEXOP_ADDSIGNED = 0x8,
    TEXOP_ADDSIGNED2X = 0x9,
    TEXOP_SUBTRACT = 0xA,
    TEXOP_ADDSMOOTH = 0xB,
    TEXOP_BLENDDIFFUSEALPHA = 0xC,
    TEXOP_BLENDTEXTUREALPHA = 0xD,
    TEXOP_BLENDFACTORALPHA = 0xE,
    TEXOP_BLENDTEXTUREALPHAPM = 0xF,
    TEXOP_BLENDCURRENTALPHA = 0x10,
    TEXOP_PREMODULATE = 0x11,
    TEXOP_MODULATEALPHA_ADDCOLOR = 0x12,
    TEXOP_MODULATECOLOR_ADDALPHA = 0x13,
    TEXOP_MODULATEINVALPHA_ADDCOLOR = 0x14,
    TEXOP_MODULATEINVCOLOR_ADDALPHA = 0x15,
    TEXOP_BUMPENVMAP = 0x16,
    TEXOP_BUMPENVMAPLUMINANCE = 0x17,
    TEXOP_DOTPRODUCT3 = 0x18,
    TEXOP_MULTIPLYADD = 0x19,
    TEXOP_LERP = 0x1A,
    TEXOP_INVALID = 0x7FFFFFFF
}

