namespace ACBindingsTest.Internal;

// ATTACK_HEIGHT
public enum ATTACK_HEIGHT : uint
{
    UNDEF_ATTACK_HEIGHT = 0x0,
    HIGH_ATTACK_HEIGHT = 0x1,
    MEDIUM_ATTACK_HEIGHT = 0x2,
    LOW_ATTACK_HEIGHT = 0x3,
    NUM_ATTACK_HEIGHTS = 0x4,
    FORCE_ATTACK_HEIGHT_32_BIT = 0x7FFFFFFF
}

