namespace ACBindingsTest.Internal;

// COMBAT_MODE
public enum COMBAT_MODE : uint
{
    UNDEF_COMBAT_MODE = 0x0,
    NONCOMBAT_COMBAT_MODE = 0x1,
    MELEE_COMBAT_MODE = 0x2,
    MISSILE_COMBAT_MODE = 0x4,
    MAGIC_COMBAT_MODE = 0x8,
    COMBAT_COMBAT_MODE = 0xE,
    VALID_COMBAT_MODES = 0xF,
    FORCE_COMBAT_MODE_32_BIT = 0x7FFFFFFF
}

