namespace ACBindingsTest.Internal;

// DAMAGE_TYPE
public enum DAMAGE_TYPE : uint
{
    UNDEF_DAMAGE_TYPE = 0x0,
    SLASH_DAMAGE_TYPE = 0x1,
    PIERCE_DAMAGE_TYPE = 0x2,
    BLUDGEON_DAMAGE_TYPE = 0x4,
    COLD_DAMAGE_TYPE = 0x8,
    FIRE_DAMAGE_TYPE = 0x10,
    ACID_DAMAGE_TYPE = 0x20,
    ELECTRIC_DAMAGE_TYPE = 0x40,
    HEALTH_DAMAGE_TYPE = 0x80,
    STAMINA_DAMAGE_TYPE = 0x100,
    MANA_DAMAGE_TYPE = 0x200,
    NETHER_DAMAGE_TYPE = 0x400,
    BASE_DAMAGE_TYPE = 0x10000000,
    FORCE_DAMAGE_TYPE_32_BIT = 0x7FFFFFFF
}

