namespace ACBindingsTest.Internal;

// UI_EFFECT_TYPE
public enum UI_EFFECT_TYPE : uint
{
    UI_EFFECT_UNDEF = 0x0,
    UI_EFFECT_MAGICAL = 0x1,
    UI_EFFECT_POISONED = 0x2,
    UI_EFFECT_BOOST_HEALTH = 0x4,
    UI_EFFECT_BOOST_MANA = 0x8,
    UI_EFFECT_BOOST_STAMINA = 0x10,
    UI_EFFECT_FIRE = 0x20,
    UI_EFFECT_LIGHTNING = 0x40,
    UI_EFFECT_FROST = 0x80,
    UI_EFFECT_ACID = 0x100,
    UI_EFFECT_BLUDGEONING = 0x200,
    UI_EFFECT_SLASHING = 0x400,
    UI_EFFECT_PIERCING = 0x800,
    UI_EFFECT_NETHER = 0x1000,
    FORCE_UI_EFFECT_TYPE_32_BIT = 0x7FFFFFFF
}

