namespace ACBindingsTest.Internal;

// UI_SELECTION_TYPE
public enum UI_SELECTION_TYPE : uint
{
    SELECTION_TYPE_UNDEF = 0x0,
    SELECTION_TYPE_ITEM = 0x1,
    SELECTION_TYPE_COMPASS_ITEM = 0x2,
    SELECTION_TYPE_MONSTER = 0x3,
    SELECTION_TYPE_PLAYER = 0x4,
    SELECTION_TYPE_UNOPENED_CORPSE = 0x5,
    FORCE_UI_SELECTION_TYPE_32_BIT = 0x7FFFFFFF
}

