namespace ACBindingsTest.Internal;

// CACHE_OBJECT_CODES
public enum CACHE_OBJECT_CODES : uint
{
    CACHE_OBJECT_LOOKING = 0x0,
    CACHE_OBJECT_IN_FILE = 0x1,
    CACHE_OBJECT_IN_MEMORY = 0x2,
    CACHE_OBJECT_INVALID = 0xFFFFFFFE,
    CACHE_OBJECT_NET_GETTING = 0xFFFFFFFF
}

