namespace ACBindingsTest.Internal;

// _D3DPRIMITIVETYPE
public enum _D3DPRIMITIVETYPE : uint
{
    D3DPT_POINTLIST = 0x1,
    D3DPT_LINELIST = 0x2,
    D3DPT_LINESTRIP = 0x3,
    D3DPT_TRIANGLELIST = 0x4,
    D3DPT_TRIANGLESTRIP = 0x5,
    D3DPT_TRIANGLEFAN = 0x6,
    D3DPT_FORCE_DWORD = 0x7FFFFFFF
}

