namespace ACBindingsTest.Internal;

// _D3DRESOURCETYPE
public enum _D3DRESOURCETYPE : uint
{
    D3DRTYPE_SURFACE = 0x1,
    D3DRTYPE_VOLUME = 0x2,
    D3DRTYPE_TEXTURE = 0x3,
    D3DRTYPE_VOLUMETEXTURE = 0x4,
    D3DRTYPE_CUBETEXTURE = 0x5,
    D3DRTYPE_VERTEXBUFFER = 0x6,
    D3DRTYPE_INDEXBUFFER = 0x7,
    D3DRTYPE_FORCE_DWORD = 0x7FFFFFFF
}

