namespace ACBindingsTest.Internal;

// AlphaTestFunc
public enum AlphaTestFunc : uint
{
    ALPHATESTFUNC_NEVER = 0x1,
    ALPHATESTFUNC_LESS = 0x2,
    ALPHATESTFUNC_EQUAL = 0x3,
    ALPHATESTFUNC_LESSEQUAL = 0x4,
    ALPHATESTFUNC_GREATER = 0x5,
    ALPHATESTFUNC_NOTEQUAL = 0x6,
    ALPHATESTFUNC_GREATEREQUAL = 0x7,
    ALPHATESTFUNC_ALWAYS = 0x8,
    ALPHATESTFUNC_INVALID = 0x7FFFFFFF
}

