namespace ACBindingsTest.Internal;

// BlendMode
public enum BlendMode : uint
{
    BLEND_ZERO = 0x1,
    BLEND_ONE = 0x2,
    BLEND_SRCCOLOR = 0x3,
    BLEND_INVSRCCOLOR = 0x4,
    BLEND_SRCALPHA = 0x5,
    BLEND_INVSRCALPHA = 0x6,
    BLEND_DSTALPHA = 0x7,
    BLEND_INVDSTALPHA = 0x8,
    BLEND_DSTCOLOR = 0x9,
    BLEND_INVDSTCOLOR = 0xA,
    BLEND_SRCALPHASAT = 0xB,
    BLEND_BOTHSRCALPHA = 0xC,
    BLEND_BOTHINVSRCALPHA = 0xD,
    BLEND_BLENDFACTOR = 0xE,
    BLEND_INVBLENDFACTOR = 0xF,
    BLEND_INVALID = 0x7FFFFFFF
}

