namespace ACBindingsTest.Internal;

// RenderPassType
public enum RenderPassType : byte
{
    RenderPass_Default = 0x0,
    RenderPass_DirectionalLightDiffuseAndSpecular = 0x1,
    RenderPass_PointLightDiffuseAndSpecular = 0x2,
    RenderPass_PointLightDiffuseAndSpecularProjector = 0x3,
    RenderPass_AmbientLight_DirectionalLightDiffuseAndSpecular = 0x4,
    RenderPass_AmbientLight_PointLightDiffuseAndSpecular = 0x5,
    RenderPass_DistanceFog = 0x6,
    RenderPass_FixedFunctionGlow = 0x7,
    RenderPass_ShaderGlow = 0x8,
    RenderPass_LandscapeShadowMap = 0x9,
    RenderPass_AlphaBlend = 0xA,
    RenderPass_AL_0DL_0PL = 0xB,
    RenderPass_AL_0DL_1PL = 0xC,
    RenderPass_AL_0DL_2PL = 0xD,
    RenderPass_AL_0DL_3PL = 0xE,
    RenderPass_AL_0DL_4PL = 0xF,
    RenderPass_AL_0DL_5PL = 0x10,
    RenderPass_AL_0DL_6PL = 0x11,
    RenderPass_AL_0DL_7PL = 0x12,
    RenderPass_AL_0DL_8PL = 0x13,
    RenderPass_AL_1DL_0PL = 0x14,
    RenderPass_AL_1DL_1PL = 0x15,
    RenderPass_AL_1DL_2PL = 0x16,
    RenderPass_AL_1DL_3PL = 0x17,
    RenderPass_AL_1DL_4PL = 0x18,
    RenderPass_AL_1DL_5PL = 0x19,
    RenderPass_AL_1DL_6PL = 0x1A,
    RenderPass_AL_1DL_7PL = 0x1B,
    RenderPass_AL_0DL_0PL_Fog = 0x1C,
    RenderPass_AL_0DL_1PL_Fog = 0x1D,
    RenderPass_AL_0DL_2PL_Fog = 0x1E,
    RenderPass_AL_0DL_3PL_Fog = 0x1F,
    RenderPass_AL_0DL_4PL_Fog = 0x20,
    RenderPass_AL_0DL_5PL_Fog = 0x21,
    RenderPass_AL_0DL_6PL_Fog = 0x22,
    RenderPass_AL_0DL_7PL_Fog = 0x23,
    RenderPass_AL_0DL_8PL_Fog = 0x24,
    RenderPass_AL_1DL_0PL_Fog = 0x25,
    RenderPass_AL_1DL_1PL_Fog = 0x26,
    RenderPass_AL_1DL_2PL_Fog = 0x27,
    RenderPass_AL_1DL_3PL_Fog = 0x28,
    RenderPass_AL_1DL_4PL_Fog = 0x29,
    RenderPass_AL_1DL_5PL_Fog = 0x2A,
    RenderPass_AL_1DL_6PL_Fog = 0x2B,
    RenderPass_AL_1DL_7PL_Fog = 0x2C,
    RenderPass_MaxPasses = 0x2D,
    RenderPass_Invalid = 0x2E
}

